services:
  nginx:
    image: nginx:latest
    container_name: tasker_nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3032:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/app
    depends_on:
      - php-fpm
    networks:
      - app-network

  node:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    container_name: tasker_node
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
    networks:
      - app-network
  
  php-fpm:
    user: "${UID:-1000}:${GID:-1000}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: docker/php.dev.Dockerfile
    container_name: tasker_php
    working_dir: /app
    command: sh -c "composer update && php-fpm"
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    depends_on:
    - postgres
    environment:
      - DB_ROOT_PASS=qwerty123
      - DB_DATABASE=test
      - DB_USERNAME=test
      - DB_PASSWORD=qwerty123
    networks:
      - app-network
  
  postgres:
    image: postgres:18
    container_name: tasker_postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRES_ROOT_PASSWORD=qwerty123
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=qwerty123
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
    - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
